import { AppProvider } from "@/contexts/app-context";
import { SyncProvider } from "@/lib/sync";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <AppProvider>
        <SyncProvider>{children}</SyncProvider>
      </AppProvider>
    </section>
  );
}
